name:                timesheet
version:             0.1.0.0
#synopsis:
#description:
#homepage:
license:             ISC
author:              Nathan Ingle
maintainer:          elgni.nahtan@gmail.com
copyright:           2020 Nathan Ingle
category:            Text

ghc-options: -Wall -Werror -O2 -Wnoncanonical-monad-instances +RTS -M3G -RTS

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - mtl
  - text
  - time

library:
  source-dirs:      src
  exposed-modules:
    - Parse
    - Validate
    - WorkDay

executables:
  timesheet:
    main:             timesheet.hs
    dependencies:
      - timesheet

tests:
  test:
    source-dirs:      test
    main:             test.hs
    dependencies:
      - timesheet
      - tasty
      - tasty-hunit
